// Autogenerated from Pigeon (v25.5.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func createConnectionError(withChannelName channelName: String) -> PigeonError {
  return PigeonError(code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.", details: "")
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

func deepEqualsMessages(_ lhs: Any?, _ rhs: Any?) -> Bool {
  let cleanLhs = nilOrValue(lhs) as Any?
  let cleanRhs = nilOrValue(rhs) as Any?
  switch (cleanLhs, cleanRhs) {
  case (nil, nil):
    return true

  case (nil, _), (_, nil):
    return false

  case is (Void, Void):
    return true

  case let (cleanLhsHashable, cleanRhsHashable) as (AnyHashable, AnyHashable):
    return cleanLhsHashable == cleanRhsHashable

  case let (cleanLhsArray, cleanRhsArray) as ([Any?], [Any?]):
    guard cleanLhsArray.count == cleanRhsArray.count else { return false }
    for (index, element) in cleanLhsArray.enumerated() {
      if !deepEqualsMessages(element, cleanRhsArray[index]) {
        return false
      }
    }
    return true

  case let (cleanLhsDictionary, cleanRhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
    guard cleanLhsDictionary.count == cleanRhsDictionary.count else { return false }
    for (key, cleanLhsValue) in cleanLhsDictionary {
      guard cleanRhsDictionary.index(forKey: key) != nil else { return false }
      if !deepEqualsMessages(cleanLhsValue, cleanRhsDictionary[key]!) {
        return false
      }
    }
    return true

  default:
    // Any other type shouldn't be able to be used with pigeon. File an issue if you find this to be untrue.
    return false
  }
}

func deepHashMessages(value: Any?, hasher: inout Hasher) {
  if let valueList = value as? [AnyHashable] {
     for item in valueList { deepHashMessages(value: item, hasher: &hasher) }
     return
  }

  if let valueDict = value as? [AnyHashable: AnyHashable] {
    for key in valueDict.keys { 
      hasher.combine(key)
      deepHashMessages(value: valueDict[key]!, hasher: &hasher)
    }
    return
  }

  if let hashableValue = value as? AnyHashable {
    hasher.combine(hashableValue.hashValue)
  }

  return hasher.combine(String(describing: value))
}

    

/// Camera facing direction
enum CameraFacing: Int {
  case back = 0
  case front = 1
}

/// Camera resolution preset
enum CameraResolution: Int {
  case low = 0
  case medium = 1
  case high = 2
  case max = 3
}

/// Bounding box of a detected barcode (normalized 0-1 coordinates)
///
/// Generated class from Pigeon that represents data sent in messages.
struct BoundingBox: Hashable {
  var left: Double
  var top: Double
  var right: Double
  var bottom: Double


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> BoundingBox? {
    let left = pigeonVar_list[0] as! Double
    let top = pigeonVar_list[1] as! Double
    let right = pigeonVar_list[2] as! Double
    let bottom = pigeonVar_list[3] as! Double

    return BoundingBox(
      left: left,
      top: top,
      right: right,
      bottom: bottom
    )
  }
  func toList() -> [Any?] {
    return [
      left,
      top,
      right,
      bottom,
    ]
  }
  static func == (lhs: BoundingBox, rhs: BoundingBox) -> Bool {
    return deepEqualsMessages(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashMessages(value: toList(), hasher: &hasher)
  }
}

/// Corner point of a barcode (normalized 0-1 coordinates)
///
/// Generated class from Pigeon that represents data sent in messages.
struct Point: Hashable {
  var x: Double
  var y: Double


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> Point? {
    let x = pigeonVar_list[0] as! Double
    let y = pigeonVar_list[1] as! Double

    return Point(
      x: x,
      y: y
    )
  }
  func toList() -> [Any?] {
    return [
      x,
      y,
    ]
  }
  static func == (lhs: Point, rhs: Point) -> Bool {
    return deepEqualsMessages(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashMessages(value: toList(), hasher: &hasher)
  }
}

/// Represents a scanned barcode result
///
/// Generated class from Pigeon that represents data sent in messages.
struct BarcodeResult: Hashable {
  /// The decoded string value of the barcode
  var value: String
  /// The format of the barcode (e.g., "qr", "ean13", "code128")
  var format: String
  /// Raw bytes of the barcode (if available)
  var rawBytes: FlutterStandardTypedData? = nil
  /// Bounding box of the barcode (normalized 0-1 coordinates)
  var boundingBox: BoundingBox? = nil
  /// Corner points of the barcode (normalized 0-1 coordinates)
  var cornerPoints: [Point]? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> BarcodeResult? {
    let value = pigeonVar_list[0] as! String
    let format = pigeonVar_list[1] as! String
    let rawBytes: FlutterStandardTypedData? = nilOrValue(pigeonVar_list[2])
    let boundingBox: BoundingBox? = nilOrValue(pigeonVar_list[3])
    let cornerPoints: [Point]? = nilOrValue(pigeonVar_list[4])

    return BarcodeResult(
      value: value,
      format: format,
      rawBytes: rawBytes,
      boundingBox: boundingBox,
      cornerPoints: cornerPoints
    )
  }
  func toList() -> [Any?] {
    return [
      value,
      format,
      rawBytes,
      boundingBox,
      cornerPoints,
    ]
  }
  static func == (lhs: BarcodeResult, rhs: BarcodeResult) -> Bool {
    return deepEqualsMessages(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashMessages(value: toList(), hasher: &hasher)
  }
}

/// Scan region (normalized 0-1 coordinates, relative to view)
///
/// Generated class from Pigeon that represents data sent in messages.
struct ScanRegion: Hashable {
  var left: Double
  var top: Double
  var width: Double
  var height: Double


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ScanRegion? {
    let left = pigeonVar_list[0] as! Double
    let top = pigeonVar_list[1] as! Double
    let width = pigeonVar_list[2] as! Double
    let height = pigeonVar_list[3] as! Double

    return ScanRegion(
      left: left,
      top: top,
      width: width,
      height: height
    )
  }
  func toList() -> [Any?] {
    return [
      left,
      top,
      width,
      height,
    ]
  }
  static func == (lhs: ScanRegion, rhs: ScanRegion) -> Bool {
    return deepEqualsMessages(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashMessages(value: toList(), hasher: &hasher)
  }
}

/// Configuration for the scanner
///
/// Generated class from Pigeon that represents data sent in messages.
struct ScannerConfig: Hashable {
  /// List of barcode formats to scan for. Null means all formats.
  var formats: [String]? = nil
  /// Whether to play a beep sound on successful scan
  var beepOnScan: Bool
  /// Whether to vibrate on successful scan
  var vibrateOnScan: Bool
  /// Whether to show torch toggle button in the scanner UI
  var showTorchButton: Bool
  /// Which camera to use (front or back)
  var cameraFacing: CameraFacing
  /// Camera resolution preset
  var resolution: CameraResolution
  /// Whether to invert colors for scanning white-on-black barcodes
  var invertColors: Bool
  /// Region of interest for scanning (null = full frame)
  var scanRegion: ScanRegion? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ScannerConfig? {
    let formats: [String]? = nilOrValue(pigeonVar_list[0])
    let beepOnScan = pigeonVar_list[1] as! Bool
    let vibrateOnScan = pigeonVar_list[2] as! Bool
    let showTorchButton = pigeonVar_list[3] as! Bool
    let cameraFacing = pigeonVar_list[4] as! CameraFacing
    let resolution = pigeonVar_list[5] as! CameraResolution
    let invertColors = pigeonVar_list[6] as! Bool
    let scanRegion: ScanRegion? = nilOrValue(pigeonVar_list[7])

    return ScannerConfig(
      formats: formats,
      beepOnScan: beepOnScan,
      vibrateOnScan: vibrateOnScan,
      showTorchButton: showTorchButton,
      cameraFacing: cameraFacing,
      resolution: resolution,
      invertColors: invertColors,
      scanRegion: scanRegion
    )
  }
  func toList() -> [Any?] {
    return [
      formats,
      beepOnScan,
      vibrateOnScan,
      showTorchButton,
      cameraFacing,
      resolution,
      invertColors,
      scanRegion,
    ]
  }
  static func == (lhs: ScannerConfig, rhs: ScannerConfig) -> Bool {
    return deepEqualsMessages(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashMessages(value: toList(), hasher: &hasher)
  }
}

/// Configuration for embedded scanner view
///
/// Generated class from Pigeon that represents data sent in messages.
struct EmbeddedScannerConfig: Hashable {
  /// List of barcode formats to scan for. Null means all formats.
  var formats: [String]? = nil
  /// Which camera to use (front or back)
  var cameraFacing: CameraFacing
  /// Camera resolution preset
  var resolution: CameraResolution
  /// Whether to invert colors for scanning white-on-black barcodes
  var invertColors: Bool
  /// Region of interest for scanning (null = full frame)
  var scanRegion: ScanRegion? = nil
  /// Debounce delay in milliseconds between same-value detections
  var debounceMs: Int64
  /// Whether to auto-zoom toward detected barcodes
  var autoZoom: Bool


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> EmbeddedScannerConfig? {
    let formats: [String]? = nilOrValue(pigeonVar_list[0])
    let cameraFacing = pigeonVar_list[1] as! CameraFacing
    let resolution = pigeonVar_list[2] as! CameraResolution
    let invertColors = pigeonVar_list[3] as! Bool
    let scanRegion: ScanRegion? = nilOrValue(pigeonVar_list[4])
    let debounceMs = pigeonVar_list[5] as! Int64
    let autoZoom = pigeonVar_list[6] as! Bool

    return EmbeddedScannerConfig(
      formats: formats,
      cameraFacing: cameraFacing,
      resolution: resolution,
      invertColors: invertColors,
      scanRegion: scanRegion,
      debounceMs: debounceMs,
      autoZoom: autoZoom
    )
  }
  func toList() -> [Any?] {
    return [
      formats,
      cameraFacing,
      resolution,
      invertColors,
      scanRegion,
      debounceMs,
      autoZoom,
    ]
  }
  static func == (lhs: EmbeddedScannerConfig, rhs: EmbeddedScannerConfig) -> Bool {
    return deepEqualsMessages(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashMessages(value: toList(), hasher: &hasher)
  }
}

/// Configuration for document scanning
///
/// Generated class from Pigeon that represents data sent in messages.
struct DocumentScanConfig: Hashable {
  /// Maximum number of pages to scan (null = unlimited)
  var maxPages: Int64? = nil
  /// Whether to allow importing from photo gallery
  var allowGalleryImport: Bool


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> DocumentScanConfig? {
    let maxPages: Int64? = nilOrValue(pigeonVar_list[0])
    let allowGalleryImport = pigeonVar_list[1] as! Bool

    return DocumentScanConfig(
      maxPages: maxPages,
      allowGalleryImport: allowGalleryImport
    )
  }
  func toList() -> [Any?] {
    return [
      maxPages,
      allowGalleryImport,
    ]
  }
  static func == (lhs: DocumentScanConfig, rhs: DocumentScanConfig) -> Bool {
    return deepEqualsMessages(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashMessages(value: toList(), hasher: &hasher)
  }
}

/// Represents a scanned document page
///
/// Generated class from Pigeon that represents data sent in messages.
struct ScannedPage: Hashable {
  /// Path to the scanned image file
  var imagePath: String
  /// Width of the image in pixels
  var width: Int64
  /// Height of the image in pixels
  var height: Int64


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ScannedPage? {
    let imagePath = pigeonVar_list[0] as! String
    let width = pigeonVar_list[1] as! Int64
    let height = pigeonVar_list[2] as! Int64

    return ScannedPage(
      imagePath: imagePath,
      width: width,
      height: height
    )
  }
  func toList() -> [Any?] {
    return [
      imagePath,
      width,
      height,
    ]
  }
  static func == (lhs: ScannedPage, rhs: ScannedPage) -> Bool {
    return deepEqualsMessages(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashMessages(value: toList(), hasher: &hasher)
  }
}

/// Result of document scanning
///
/// Generated class from Pigeon that represents data sent in messages.
struct DocumentScanResult: Hashable {
  /// List of scanned pages
  var pages: [ScannedPage]
  /// Path to combined PDF (if generated)
  var pdfPath: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> DocumentScanResult? {
    let pages = pigeonVar_list[0] as! [ScannedPage]
    let pdfPath: String? = nilOrValue(pigeonVar_list[1])

    return DocumentScanResult(
      pages: pages,
      pdfPath: pdfPath
    )
  }
  func toList() -> [Any?] {
    return [
      pages,
      pdfPath,
    ]
  }
  static func == (lhs: DocumentScanResult, rhs: DocumentScanResult) -> Bool {
    return deepEqualsMessages(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashMessages(value: toList(), hasher: &hasher)
  }
}

private class MessagesPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return CameraFacing(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return CameraResolution(rawValue: enumResultAsInt)
      }
      return nil
    case 131:
      return BoundingBox.fromList(self.readValue() as! [Any?])
    case 132:
      return Point.fromList(self.readValue() as! [Any?])
    case 133:
      return BarcodeResult.fromList(self.readValue() as! [Any?])
    case 134:
      return ScanRegion.fromList(self.readValue() as! [Any?])
    case 135:
      return ScannerConfig.fromList(self.readValue() as! [Any?])
    case 136:
      return EmbeddedScannerConfig.fromList(self.readValue() as! [Any?])
    case 137:
      return DocumentScanConfig.fromList(self.readValue() as! [Any?])
    case 138:
      return ScannedPage.fromList(self.readValue() as! [Any?])
    case 139:
      return DocumentScanResult.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class MessagesPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? CameraFacing {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? CameraResolution {
      super.writeByte(130)
      super.writeValue(value.rawValue)
    } else if let value = value as? BoundingBox {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else if let value = value as? Point {
      super.writeByte(132)
      super.writeValue(value.toList())
    } else if let value = value as? BarcodeResult {
      super.writeByte(133)
      super.writeValue(value.toList())
    } else if let value = value as? ScanRegion {
      super.writeByte(134)
      super.writeValue(value.toList())
    } else if let value = value as? ScannerConfig {
      super.writeByte(135)
      super.writeValue(value.toList())
    } else if let value = value as? EmbeddedScannerConfig {
      super.writeByte(136)
      super.writeValue(value.toList())
    } else if let value = value as? DocumentScanConfig {
      super.writeByte(137)
      super.writeValue(value.toList())
    } else if let value = value as? ScannedPage {
      super.writeByte(138)
      super.writeValue(value.toList())
    } else if let value = value as? DocumentScanResult {
      super.writeByte(139)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class MessagesPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return MessagesPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return MessagesPigeonCodecWriter(data: data)
  }
}

class MessagesPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = MessagesPigeonCodec(readerWriter: MessagesPigeonCodecReaderWriter())
}


/// Host API - methods called from Dart to native
///
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol ScannerHostApi {
  /// Opens the scanner and returns the scanned barcode, or null if cancelled
  func startScan(config: ScannerConfig, completion: @escaping (Result<BarcodeResult?, Error>) -> Void)
  /// Checks if the device supports barcode scanning
  func isSupported() throws -> Bool
  /// Checks if torch/flash is available
  func isTorchAvailable() throws -> Bool
  /// Sets the torch state for the embedded scanner
  func setTorch(enabled: Bool) throws
  /// Gets current torch state
  func getTorchState() throws -> Bool
  /// Checks if document scanning is supported
  func isDocumentScanSupported() throws -> Bool
  /// Opens the document scanner and returns scanned pages, or null if cancelled
  func startDocumentScan(config: DocumentScanConfig, completion: @escaping (Result<DocumentScanResult?, Error>) -> Void)
  /// Scans barcode from an image file path
  func scanFromImagePath(imagePath: String, formats: [String]?, completion: @escaping (Result<BarcodeResult?, Error>) -> Void)
  /// Opens gallery to pick an image and scan barcode from it
  func scanFromGallery(formats: [String]?, completion: @escaping (Result<BarcodeResult?, Error>) -> Void)
  /// Pre-initializes the scanner for faster startup
  func warmUp() throws
  /// Updates embedded scanner configuration at runtime
  func updateEmbeddedConfig(config: EmbeddedScannerConfig) throws
  /// Switches camera (front/back) on embedded scanner
  func switchCamera() throws
  /// Sets zoom level (1.0 = no zoom)
  func setZoom(zoom: Double) throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class ScannerHostApiSetup {
  static var codec: FlutterStandardMessageCodec { MessagesPigeonCodec.shared }
  /// Sets up an instance of `ScannerHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: ScannerHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    /// Opens the scanner and returns the scanned barcode, or null if cancelled
    let startScanChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.scankit.ScannerHostApi.startScan\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      startScanChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let configArg = args[0] as! ScannerConfig
        api.startScan(config: configArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      startScanChannel.setMessageHandler(nil)
    }
    /// Checks if the device supports barcode scanning
    let isSupportedChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.scankit.ScannerHostApi.isSupported\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      isSupportedChannel.setMessageHandler { _, reply in
        do {
          let result = try api.isSupported()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      isSupportedChannel.setMessageHandler(nil)
    }
    /// Checks if torch/flash is available
    let isTorchAvailableChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.scankit.ScannerHostApi.isTorchAvailable\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      isTorchAvailableChannel.setMessageHandler { _, reply in
        do {
          let result = try api.isTorchAvailable()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      isTorchAvailableChannel.setMessageHandler(nil)
    }
    /// Sets the torch state for the embedded scanner
    let setTorchChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.scankit.ScannerHostApi.setTorch\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setTorchChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let enabledArg = args[0] as! Bool
        do {
          try api.setTorch(enabled: enabledArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setTorchChannel.setMessageHandler(nil)
    }
    /// Gets current torch state
    let getTorchStateChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.scankit.ScannerHostApi.getTorchState\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getTorchStateChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getTorchState()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getTorchStateChannel.setMessageHandler(nil)
    }
    /// Checks if document scanning is supported
    let isDocumentScanSupportedChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.scankit.ScannerHostApi.isDocumentScanSupported\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      isDocumentScanSupportedChannel.setMessageHandler { _, reply in
        do {
          let result = try api.isDocumentScanSupported()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      isDocumentScanSupportedChannel.setMessageHandler(nil)
    }
    /// Opens the document scanner and returns scanned pages, or null if cancelled
    let startDocumentScanChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.scankit.ScannerHostApi.startDocumentScan\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      startDocumentScanChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let configArg = args[0] as! DocumentScanConfig
        api.startDocumentScan(config: configArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      startDocumentScanChannel.setMessageHandler(nil)
    }
    /// Scans barcode from an image file path
    let scanFromImagePathChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.scankit.ScannerHostApi.scanFromImagePath\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      scanFromImagePathChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let imagePathArg = args[0] as! String
        let formatsArg: [String]? = nilOrValue(args[1])
        api.scanFromImagePath(imagePath: imagePathArg, formats: formatsArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      scanFromImagePathChannel.setMessageHandler(nil)
    }
    /// Opens gallery to pick an image and scan barcode from it
    let scanFromGalleryChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.scankit.ScannerHostApi.scanFromGallery\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      scanFromGalleryChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let formatsArg: [String]? = nilOrValue(args[0])
        api.scanFromGallery(formats: formatsArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      scanFromGalleryChannel.setMessageHandler(nil)
    }
    /// Pre-initializes the scanner for faster startup
    let warmUpChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.scankit.ScannerHostApi.warmUp\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      warmUpChannel.setMessageHandler { _, reply in
        do {
          try api.warmUp()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      warmUpChannel.setMessageHandler(nil)
    }
    /// Updates embedded scanner configuration at runtime
    let updateEmbeddedConfigChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.scankit.ScannerHostApi.updateEmbeddedConfig\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      updateEmbeddedConfigChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let configArg = args[0] as! EmbeddedScannerConfig
        do {
          try api.updateEmbeddedConfig(config: configArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      updateEmbeddedConfigChannel.setMessageHandler(nil)
    }
    /// Switches camera (front/back) on embedded scanner
    let switchCameraChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.scankit.ScannerHostApi.switchCamera\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      switchCameraChannel.setMessageHandler { _, reply in
        do {
          try api.switchCamera()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      switchCameraChannel.setMessageHandler(nil)
    }
    /// Sets zoom level (1.0 = no zoom)
    let setZoomChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.scankit.ScannerHostApi.setZoom\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setZoomChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let zoomArg = args[0] as! Double
        do {
          try api.setZoom(zoom: zoomArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setZoomChannel.setMessageHandler(nil)
    }
  }
}
/// Flutter API - methods called from native to Dart (for streaming results)
///
/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol ScannerFlutterApiProtocol {
  /// Called when a barcode is detected in embedded scanner mode
  func onBarcodeDetected(barcode barcodeArg: BarcodeResult, completion: @escaping (Result<Void, PigeonError>) -> Void)
  /// Called when torch state changes
  func onTorchStateChanged(enabled enabledArg: Bool, completion: @escaping (Result<Void, PigeonError>) -> Void)
  /// Called when an error occurs
  func onError(code codeArg: String, message messageArg: String, completion: @escaping (Result<Void, PigeonError>) -> Void)
  /// Called when camera is switched
  func onCameraSwitched(facing facingArg: CameraFacing, completion: @escaping (Result<Void, PigeonError>) -> Void)
  /// Called when zoom level changes
  func onZoomChanged(zoom zoomArg: Double, completion: @escaping (Result<Void, PigeonError>) -> Void)
}
class ScannerFlutterApi: ScannerFlutterApiProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: MessagesPigeonCodec {
    return MessagesPigeonCodec.shared
  }
  /// Called when a barcode is detected in embedded scanner mode
  func onBarcodeDetected(barcode barcodeArg: BarcodeResult, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.scankit.ScannerFlutterApi.onBarcodeDetected\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([barcodeArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  /// Called when torch state changes
  func onTorchStateChanged(enabled enabledArg: Bool, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.scankit.ScannerFlutterApi.onTorchStateChanged\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([enabledArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  /// Called when an error occurs
  func onError(code codeArg: String, message messageArg: String, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.scankit.ScannerFlutterApi.onError\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([codeArg, messageArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  /// Called when camera is switched
  func onCameraSwitched(facing facingArg: CameraFacing, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.scankit.ScannerFlutterApi.onCameraSwitched\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([facingArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  /// Called when zoom level changes
  func onZoomChanged(zoom zoomArg: Double, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.scankit.ScannerFlutterApi.onZoomChanged\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([zoomArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
}
