// Autogenerated from Pigeon (v25.5.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package dev.scankit.scankit

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object MessagesPigeonUtils {

  fun createConnectionError(channelName: String): FlutterError {
    return FlutterError("channel-error",  "Unable to establish connection on channel: '$channelName'.", "")  }

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a is ByteArray && b is ByteArray) {
        return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
        return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
        return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
        return a.contentEquals(b)
    }
    if (a is Array<*> && b is Array<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is List<*> && b is List<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      return a.size == b.size && a.all {
          (b as Map<Any?, Any?>).containsKey(it.key) &&
          deepEquals(it.value, b[it.key])
      }
    }
    return a == b
  }
      
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

/** Camera facing direction */
enum class CameraFacing(val raw: Int) {
  BACK(0),
  FRONT(1);

  companion object {
    fun ofRaw(raw: Int): CameraFacing? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Camera resolution preset */
enum class CameraResolution(val raw: Int) {
  LOW(0),
  MEDIUM(1),
  HIGH(2),
  MAX(3);

  companion object {
    fun ofRaw(raw: Int): CameraResolution? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/**
 * Bounding box of a detected barcode (normalized 0-1 coordinates)
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class BoundingBox (
  val left: Double,
  val top: Double,
  val right: Double,
  val bottom: Double
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): BoundingBox {
      val left = pigeonVar_list[0] as Double
      val top = pigeonVar_list[1] as Double
      val right = pigeonVar_list[2] as Double
      val bottom = pigeonVar_list[3] as Double
      return BoundingBox(left, top, right, bottom)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      left,
      top,
      right,
      bottom,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is BoundingBox) {
      return false
    }
    if (this === other) {
      return true
    }
    return MessagesPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/**
 * Corner point of a barcode (normalized 0-1 coordinates)
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class Point (
  val x: Double,
  val y: Double
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): Point {
      val x = pigeonVar_list[0] as Double
      val y = pigeonVar_list[1] as Double
      return Point(x, y)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      x,
      y,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is Point) {
      return false
    }
    if (this === other) {
      return true
    }
    return MessagesPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/**
 * Represents a scanned barcode result
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class BarcodeResult (
  /** The decoded string value of the barcode */
  val value: String,
  /** The format of the barcode (e.g., "qr", "ean13", "code128") */
  val format: String,
  /** Raw bytes of the barcode (if available) */
  val rawBytes: ByteArray? = null,
  /** Bounding box of the barcode (normalized 0-1 coordinates) */
  val boundingBox: BoundingBox? = null,
  /** Corner points of the barcode (normalized 0-1 coordinates) */
  val cornerPoints: List<Point>? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): BarcodeResult {
      val value = pigeonVar_list[0] as String
      val format = pigeonVar_list[1] as String
      val rawBytes = pigeonVar_list[2] as ByteArray?
      val boundingBox = pigeonVar_list[3] as BoundingBox?
      val cornerPoints = pigeonVar_list[4] as List<Point>?
      return BarcodeResult(value, format, rawBytes, boundingBox, cornerPoints)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      value,
      format,
      rawBytes,
      boundingBox,
      cornerPoints,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is BarcodeResult) {
      return false
    }
    if (this === other) {
      return true
    }
    return MessagesPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/**
 * Scan region (normalized 0-1 coordinates, relative to view)
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class ScanRegion (
  val left: Double,
  val top: Double,
  val width: Double,
  val height: Double
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ScanRegion {
      val left = pigeonVar_list[0] as Double
      val top = pigeonVar_list[1] as Double
      val width = pigeonVar_list[2] as Double
      val height = pigeonVar_list[3] as Double
      return ScanRegion(left, top, width, height)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      left,
      top,
      width,
      height,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is ScanRegion) {
      return false
    }
    if (this === other) {
      return true
    }
    return MessagesPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/**
 * Configuration for the scanner
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class ScannerConfig (
  /** List of barcode formats to scan for. Null means all formats. */
  val formats: List<String>? = null,
  /** Whether to play a beep sound on successful scan */
  val beepOnScan: Boolean,
  /** Whether to vibrate on successful scan */
  val vibrateOnScan: Boolean,
  /** Whether to show torch toggle button in the scanner UI */
  val showTorchButton: Boolean,
  /** Which camera to use (front or back) */
  val cameraFacing: CameraFacing,
  /** Camera resolution preset */
  val resolution: CameraResolution,
  /** Whether to invert colors for scanning white-on-black barcodes */
  val invertColors: Boolean,
  /** Region of interest for scanning (null = full frame) */
  val scanRegion: ScanRegion? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ScannerConfig {
      val formats = pigeonVar_list[0] as List<String>?
      val beepOnScan = pigeonVar_list[1] as Boolean
      val vibrateOnScan = pigeonVar_list[2] as Boolean
      val showTorchButton = pigeonVar_list[3] as Boolean
      val cameraFacing = pigeonVar_list[4] as CameraFacing
      val resolution = pigeonVar_list[5] as CameraResolution
      val invertColors = pigeonVar_list[6] as Boolean
      val scanRegion = pigeonVar_list[7] as ScanRegion?
      return ScannerConfig(formats, beepOnScan, vibrateOnScan, showTorchButton, cameraFacing, resolution, invertColors, scanRegion)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      formats,
      beepOnScan,
      vibrateOnScan,
      showTorchButton,
      cameraFacing,
      resolution,
      invertColors,
      scanRegion,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is ScannerConfig) {
      return false
    }
    if (this === other) {
      return true
    }
    return MessagesPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/**
 * Configuration for embedded scanner view
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class EmbeddedScannerConfig (
  /** List of barcode formats to scan for. Null means all formats. */
  val formats: List<String>? = null,
  /** Which camera to use (front or back) */
  val cameraFacing: CameraFacing,
  /** Camera resolution preset */
  val resolution: CameraResolution,
  /** Whether to invert colors for scanning white-on-black barcodes */
  val invertColors: Boolean,
  /** Region of interest for scanning (null = full frame) */
  val scanRegion: ScanRegion? = null,
  /** Debounce delay in milliseconds between same-value detections */
  val debounceMs: Long,
  /** Whether to auto-zoom toward detected barcodes */
  val autoZoom: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): EmbeddedScannerConfig {
      val formats = pigeonVar_list[0] as List<String>?
      val cameraFacing = pigeonVar_list[1] as CameraFacing
      val resolution = pigeonVar_list[2] as CameraResolution
      val invertColors = pigeonVar_list[3] as Boolean
      val scanRegion = pigeonVar_list[4] as ScanRegion?
      val debounceMs = pigeonVar_list[5] as Long
      val autoZoom = pigeonVar_list[6] as Boolean
      return EmbeddedScannerConfig(formats, cameraFacing, resolution, invertColors, scanRegion, debounceMs, autoZoom)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      formats,
      cameraFacing,
      resolution,
      invertColors,
      scanRegion,
      debounceMs,
      autoZoom,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is EmbeddedScannerConfig) {
      return false
    }
    if (this === other) {
      return true
    }
    return MessagesPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/**
 * Configuration for document scanning
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class DocumentScanConfig (
  /** Maximum number of pages to scan (null = unlimited) */
  val maxPages: Long? = null,
  /** Whether to allow importing from photo gallery */
  val allowGalleryImport: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): DocumentScanConfig {
      val maxPages = pigeonVar_list[0] as Long?
      val allowGalleryImport = pigeonVar_list[1] as Boolean
      return DocumentScanConfig(maxPages, allowGalleryImport)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      maxPages,
      allowGalleryImport,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is DocumentScanConfig) {
      return false
    }
    if (this === other) {
      return true
    }
    return MessagesPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/**
 * Represents a scanned document page
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class ScannedPage (
  /** Path to the scanned image file */
  val imagePath: String,
  /** Width of the image in pixels */
  val width: Long,
  /** Height of the image in pixels */
  val height: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ScannedPage {
      val imagePath = pigeonVar_list[0] as String
      val width = pigeonVar_list[1] as Long
      val height = pigeonVar_list[2] as Long
      return ScannedPage(imagePath, width, height)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      imagePath,
      width,
      height,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is ScannedPage) {
      return false
    }
    if (this === other) {
      return true
    }
    return MessagesPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/**
 * Result of document scanning
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class DocumentScanResult (
  /** List of scanned pages */
  val pages: List<ScannedPage>,
  /** Path to combined PDF (if generated) */
  val pdfPath: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): DocumentScanResult {
      val pages = pigeonVar_list[0] as List<ScannedPage>
      val pdfPath = pigeonVar_list[1] as String?
      return DocumentScanResult(pages, pdfPath)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      pages,
      pdfPath,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is DocumentScanResult) {
      return false
    }
    if (this === other) {
      return true
    }
    return MessagesPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}
private open class MessagesPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          CameraFacing.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          CameraResolution.ofRaw(it.toInt())
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          BoundingBox.fromList(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          Point.fromList(it)
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          BarcodeResult.fromList(it)
        }
      }
      134.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ScanRegion.fromList(it)
        }
      }
      135.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ScannerConfig.fromList(it)
        }
      }
      136.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          EmbeddedScannerConfig.fromList(it)
        }
      }
      137.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          DocumentScanConfig.fromList(it)
        }
      }
      138.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ScannedPage.fromList(it)
        }
      }
      139.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          DocumentScanResult.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is CameraFacing -> {
        stream.write(129)
        writeValue(stream, value.raw)
      }
      is CameraResolution -> {
        stream.write(130)
        writeValue(stream, value.raw)
      }
      is BoundingBox -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is Point -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      is BarcodeResult -> {
        stream.write(133)
        writeValue(stream, value.toList())
      }
      is ScanRegion -> {
        stream.write(134)
        writeValue(stream, value.toList())
      }
      is ScannerConfig -> {
        stream.write(135)
        writeValue(stream, value.toList())
      }
      is EmbeddedScannerConfig -> {
        stream.write(136)
        writeValue(stream, value.toList())
      }
      is DocumentScanConfig -> {
        stream.write(137)
        writeValue(stream, value.toList())
      }
      is ScannedPage -> {
        stream.write(138)
        writeValue(stream, value.toList())
      }
      is DocumentScanResult -> {
        stream.write(139)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/**
 * Host API - methods called from Dart to native
 *
 * Generated interface from Pigeon that represents a handler of messages from Flutter.
 */
interface ScannerHostApi {
  /** Opens the scanner and returns the scanned barcode, or null if cancelled */
  fun startScan(config: ScannerConfig, callback: (Result<BarcodeResult?>) -> Unit)
  /** Checks if the device supports barcode scanning */
  fun isSupported(): Boolean
  /** Checks if torch/flash is available */
  fun isTorchAvailable(): Boolean
  /** Sets the torch state for the embedded scanner */
  fun setTorch(enabled: Boolean)
  /** Gets current torch state */
  fun getTorchState(): Boolean
  /** Checks if document scanning is supported */
  fun isDocumentScanSupported(): Boolean
  /** Opens the document scanner and returns scanned pages, or null if cancelled */
  fun startDocumentScan(config: DocumentScanConfig, callback: (Result<DocumentScanResult?>) -> Unit)
  /** Scans barcode from an image file path */
  fun scanFromImagePath(imagePath: String, formats: List<String>?, callback: (Result<BarcodeResult?>) -> Unit)
  /** Opens gallery to pick an image and scan barcode from it */
  fun scanFromGallery(formats: List<String>?, callback: (Result<BarcodeResult?>) -> Unit)
  /** Pre-initializes the scanner for faster startup */
  fun warmUp()
  /** Updates embedded scanner configuration at runtime */
  fun updateEmbeddedConfig(config: EmbeddedScannerConfig)
  /** Switches camera (front/back) on embedded scanner */
  fun switchCamera()
  /** Sets zoom level (1.0 = no zoom) */
  fun setZoom(zoom: Double)

  companion object {
    /** The codec used by ScannerHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      MessagesPigeonCodec()
    }
    /** Sets up an instance of `ScannerHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: ScannerHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.scankit.ScannerHostApi.startScan$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val configArg = args[0] as ScannerConfig
            api.startScan(configArg) { result: Result<BarcodeResult?> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.scankit.ScannerHostApi.isSupported$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.isSupported())
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.scankit.ScannerHostApi.isTorchAvailable$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.isTorchAvailable())
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.scankit.ScannerHostApi.setTorch$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val enabledArg = args[0] as Boolean
            val wrapped: List<Any?> = try {
              api.setTorch(enabledArg)
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.scankit.ScannerHostApi.getTorchState$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.getTorchState())
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.scankit.ScannerHostApi.isDocumentScanSupported$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.isDocumentScanSupported())
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.scankit.ScannerHostApi.startDocumentScan$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val configArg = args[0] as DocumentScanConfig
            api.startDocumentScan(configArg) { result: Result<DocumentScanResult?> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.scankit.ScannerHostApi.scanFromImagePath$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val imagePathArg = args[0] as String
            val formatsArg = args[1] as List<String>?
            api.scanFromImagePath(imagePathArg, formatsArg) { result: Result<BarcodeResult?> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.scankit.ScannerHostApi.scanFromGallery$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val formatsArg = args[0] as List<String>?
            api.scanFromGallery(formatsArg) { result: Result<BarcodeResult?> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.scankit.ScannerHostApi.warmUp$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.warmUp()
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.scankit.ScannerHostApi.updateEmbeddedConfig$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val configArg = args[0] as EmbeddedScannerConfig
            val wrapped: List<Any?> = try {
              api.updateEmbeddedConfig(configArg)
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.scankit.ScannerHostApi.switchCamera$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.switchCamera()
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.scankit.ScannerHostApi.setZoom$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val zoomArg = args[0] as Double
            val wrapped: List<Any?> = try {
              api.setZoom(zoomArg)
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/**
 * Flutter API - methods called from native to Dart (for streaming results)
 *
 * Generated class from Pigeon that represents Flutter messages that can be called from Kotlin.
 */
class ScannerFlutterApi(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by ScannerFlutterApi. */
    val codec: MessageCodec<Any?> by lazy {
      MessagesPigeonCodec()
    }
  }
  /** Called when a barcode is detected in embedded scanner mode */
  fun onBarcodeDetected(barcodeArg: BarcodeResult, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.scankit.ScannerFlutterApi.onBarcodeDetected$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(barcodeArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(MessagesPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  /** Called when torch state changes */
  fun onTorchStateChanged(enabledArg: Boolean, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.scankit.ScannerFlutterApi.onTorchStateChanged$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(enabledArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(MessagesPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  /** Called when an error occurs */
  fun onError(codeArg: String, messageArg: String, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.scankit.ScannerFlutterApi.onError$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(codeArg, messageArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(MessagesPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  /** Called when camera is switched */
  fun onCameraSwitched(facingArg: CameraFacing, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.scankit.ScannerFlutterApi.onCameraSwitched$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(facingArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(MessagesPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  /** Called when zoom level changes */
  fun onZoomChanged(zoomArg: Double, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.scankit.ScannerFlutterApi.onZoomChanged$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(zoomArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(MessagesPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
}
